### PR TITLE
add Valentine plugin

### PR DESCRIPTION
**Pull request by RustoMCSpit**
im not sure if i did everything right, the .yaml is definitely wrong. this is my first attempt so sorry!

https://github.com/Tote-Bag-Labs/Valentine

### CODE REVIEW

**Comment by RustoMCSpit** [comment]
i only included the linux version here btw

**Comment by kmturley** [comment]
Thanks for finding and contibuting this plugin.

Validation is erroring with:
`TypeError: pkgVersion.files.forEach is not a function`

If you compare to another yaml file you will see you are missing hyphens `-` at the beginning of lines, which turns an object into an array

Screenshot 2024-12-03 at 9 21 37 PM

You also need to nested it inside a folder called valentine, matching the folder structure of the other plugins.
And please add Mac and Windows files too: https://github.com/tote-bag-labs/valentine/releases/tag/v1.0.1

Let me know if you have difficulty with it, I could add it if you want.
Thanks!

**Comment by RustoMCSpit** [comment]
i'll try get around to it soon, if the developers do not support it does that matter? how do i ensure tote-bag-labs has access to updating their own plugin to prevent malicious actors

**Comment by RustoMCSpit** [comment]
@kmturley it works now

**Comment by RustoMCSpit** [comment]
youll have to check if the mac files are documented right

**Comment by kmturley** [comment]
Thanks this is great. I had to make a few adjustments:
- Extra folder for plugin name
- Update author name
- Reordered platforms
- Updated description

Opened as a PR here:
https://github.com/open-audio-stack/open-audio-stack-registry/pull/38

**Pull request closed without merging**
