### PR TITLE
add jc303 plugin

### PR DESCRIPTION
**Pull request by RustoMCSpit**
https://github.com/midilab/jc303

### CODE REVIEW

**Comment by RustoMCSpit** [comment]
@kmturley if theres a website link "element"(?) please add it https://midilab.co/jc303/

**Comment by kmturley** [comment]
I made a few adjustments and added here:
https://github.com/open-audio-stack/open-audio-stack-registry/pull/39

Thanks this saves me a lot of time to find and add the metadata!
I just have to review it :)

**Comment by RustoMCSpit** [comment]
> I made a few adjustments and added here: #39
> 
> Thanks this saves me a lot of time to find and add the metadata! I just have to review it :)

should i import the owlplug ones now? im going to add a lot more plugins however i find the c note standard really bad for instruments. there should be a before vs after of a sine wave playing a standardised melody, bass, and harmony, and then all together and then the instrument (so 8 audio files). that little song would naturally become the open audio theme song. that'll have to do until people can start sending in reviews / presets (both of which should have documentation detailing how audio can be attached to them).

**Comment by RustoMCSpit** [comment]
lastly, if a plugin is both an instrument and an effect, such as surge xt (it can take audio in) what do we label it as. technically speaking, it's always an instrument as it is sidechaining the audio into itself as an instrument but still. actually no, i think it just is an instrument. is it possible to be both effect and instrument?

**Comment by kmturley** [comment]
Owlplug plugins could be converted using a script to save time.
So I think your time is better spent finding other plugins which could be added which are not in either registry.

**Pull request closed without merging**
